<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlbixdd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlbixdd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGlbixdd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGlbixdd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGlbixdd\appProdProjectContainer([
    'container.build_hash' => 'Glbixdd',
    'container.build_id' => '0536a12a',
    'container.build_time' => 1568802100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlbixdd');
